// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cv.proto

package ru.itis.hrservice.grpc.pb.cv;

public interface CVResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CVResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string skill = 2;</code>
   * @return The skill.
   */
  java.lang.String getSkill();
  /**
   * <code>string skill = 2;</code>
   * @return The bytes for skill.
   */
  com.google.protobuf.ByteString
      getSkillBytes();
}
