// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cv.proto

package ru.itis.hrservice.grpc.pb.cv;

public interface GetAllCVsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllCVsRequest)
    com.google.protobuf.MessageOrBuilder {
}
