// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job.proto

package ru.itis.hrservice.grpc.pb.job;

public interface GetAllJobsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllJobsRequest)
    com.google.protobuf.MessageOrBuilder {
}
