// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job.proto

package ru.itis.hrservice.grpc.pb.job;

/**
 * Protobuf type {@code GetAllJobsResponse}
 */
public final class GetAllJobsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetAllJobsResponse)
    GetAllJobsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAllJobsResponse.newBuilder() to construct.
  private GetAllJobsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAllJobsResponse() {
    jobs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAllJobsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itis.hrservice.grpc.pb.job.Job.internal_static_GetAllJobsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itis.hrservice.grpc.pb.job.Job.internal_static_GetAllJobsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse.class, ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse.Builder.class);
  }

  public static final int JOBS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<ru.itis.hrservice.grpc.pb.job.JobResponse> jobs_;
  /**
   * <code>repeated .JobResponse jobs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<ru.itis.hrservice.grpc.pb.job.JobResponse> getJobsList() {
    return jobs_;
  }
  /**
   * <code>repeated .JobResponse jobs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ru.itis.hrservice.grpc.pb.job.JobResponseOrBuilder> 
      getJobsOrBuilderList() {
    return jobs_;
  }
  /**
   * <code>repeated .JobResponse jobs = 1;</code>
   */
  @java.lang.Override
  public int getJobsCount() {
    return jobs_.size();
  }
  /**
   * <code>repeated .JobResponse jobs = 1;</code>
   */
  @java.lang.Override
  public ru.itis.hrservice.grpc.pb.job.JobResponse getJobs(int index) {
    return jobs_.get(index);
  }
  /**
   * <code>repeated .JobResponse jobs = 1;</code>
   */
  @java.lang.Override
  public ru.itis.hrservice.grpc.pb.job.JobResponseOrBuilder getJobsOrBuilder(
      int index) {
    return jobs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < jobs_.size(); i++) {
      output.writeMessage(1, jobs_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < jobs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, jobs_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse)) {
      return super.equals(obj);
    }
    ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse other = (ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse) obj;

    if (!getJobsList()
        .equals(other.getJobsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getJobsCount() > 0) {
      hash = (37 * hash) + JOBS_FIELD_NUMBER;
      hash = (53 * hash) + getJobsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetAllJobsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetAllJobsResponse)
      ru.itis.hrservice.grpc.pb.job.GetAllJobsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itis.hrservice.grpc.pb.job.Job.internal_static_GetAllJobsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itis.hrservice.grpc.pb.job.Job.internal_static_GetAllJobsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse.class, ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse.Builder.class);
    }

    // Construct using ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (jobsBuilder_ == null) {
        jobs_ = java.util.Collections.emptyList();
      } else {
        jobs_ = null;
        jobsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itis.hrservice.grpc.pb.job.Job.internal_static_GetAllJobsResponse_descriptor;
    }

    @java.lang.Override
    public ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse getDefaultInstanceForType() {
      return ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse build() {
      ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse buildPartial() {
      ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse result = new ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse result) {
      if (jobsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          jobs_ = java.util.Collections.unmodifiableList(jobs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.jobs_ = jobs_;
      } else {
        result.jobs_ = jobsBuilder_.build();
      }
    }

    private void buildPartial0(ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse) {
        return mergeFrom((ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse other) {
      if (other == ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse.getDefaultInstance()) return this;
      if (jobsBuilder_ == null) {
        if (!other.jobs_.isEmpty()) {
          if (jobs_.isEmpty()) {
            jobs_ = other.jobs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureJobsIsMutable();
            jobs_.addAll(other.jobs_);
          }
          onChanged();
        }
      } else {
        if (!other.jobs_.isEmpty()) {
          if (jobsBuilder_.isEmpty()) {
            jobsBuilder_.dispose();
            jobsBuilder_ = null;
            jobs_ = other.jobs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            jobsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getJobsFieldBuilder() : null;
          } else {
            jobsBuilder_.addAllMessages(other.jobs_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ru.itis.hrservice.grpc.pb.job.JobResponse m =
                  input.readMessage(
                      ru.itis.hrservice.grpc.pb.job.JobResponse.parser(),
                      extensionRegistry);
              if (jobsBuilder_ == null) {
                ensureJobsIsMutable();
                jobs_.add(m);
              } else {
                jobsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<ru.itis.hrservice.grpc.pb.job.JobResponse> jobs_ =
      java.util.Collections.emptyList();
    private void ensureJobsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        jobs_ = new java.util.ArrayList<ru.itis.hrservice.grpc.pb.job.JobResponse>(jobs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.itis.hrservice.grpc.pb.job.JobResponse, ru.itis.hrservice.grpc.pb.job.JobResponse.Builder, ru.itis.hrservice.grpc.pb.job.JobResponseOrBuilder> jobsBuilder_;

    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public java.util.List<ru.itis.hrservice.grpc.pb.job.JobResponse> getJobsList() {
      if (jobsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(jobs_);
      } else {
        return jobsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public int getJobsCount() {
      if (jobsBuilder_ == null) {
        return jobs_.size();
      } else {
        return jobsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public ru.itis.hrservice.grpc.pb.job.JobResponse getJobs(int index) {
      if (jobsBuilder_ == null) {
        return jobs_.get(index);
      } else {
        return jobsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public Builder setJobs(
        int index, ru.itis.hrservice.grpc.pb.job.JobResponse value) {
      if (jobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobsIsMutable();
        jobs_.set(index, value);
        onChanged();
      } else {
        jobsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public Builder setJobs(
        int index, ru.itis.hrservice.grpc.pb.job.JobResponse.Builder builderForValue) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.set(index, builderForValue.build());
        onChanged();
      } else {
        jobsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public Builder addJobs(ru.itis.hrservice.grpc.pb.job.JobResponse value) {
      if (jobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobsIsMutable();
        jobs_.add(value);
        onChanged();
      } else {
        jobsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public Builder addJobs(
        int index, ru.itis.hrservice.grpc.pb.job.JobResponse value) {
      if (jobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobsIsMutable();
        jobs_.add(index, value);
        onChanged();
      } else {
        jobsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public Builder addJobs(
        ru.itis.hrservice.grpc.pb.job.JobResponse.Builder builderForValue) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.add(builderForValue.build());
        onChanged();
      } else {
        jobsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public Builder addJobs(
        int index, ru.itis.hrservice.grpc.pb.job.JobResponse.Builder builderForValue) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.add(index, builderForValue.build());
        onChanged();
      } else {
        jobsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public Builder addAllJobs(
        java.lang.Iterable<? extends ru.itis.hrservice.grpc.pb.job.JobResponse> values) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, jobs_);
        onChanged();
      } else {
        jobsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public Builder clearJobs() {
      if (jobsBuilder_ == null) {
        jobs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        jobsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public Builder removeJobs(int index) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.remove(index);
        onChanged();
      } else {
        jobsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public ru.itis.hrservice.grpc.pb.job.JobResponse.Builder getJobsBuilder(
        int index) {
      return getJobsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public ru.itis.hrservice.grpc.pb.job.JobResponseOrBuilder getJobsOrBuilder(
        int index) {
      if (jobsBuilder_ == null) {
        return jobs_.get(index);  } else {
        return jobsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public java.util.List<? extends ru.itis.hrservice.grpc.pb.job.JobResponseOrBuilder> 
         getJobsOrBuilderList() {
      if (jobsBuilder_ != null) {
        return jobsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(jobs_);
      }
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public ru.itis.hrservice.grpc.pb.job.JobResponse.Builder addJobsBuilder() {
      return getJobsFieldBuilder().addBuilder(
          ru.itis.hrservice.grpc.pb.job.JobResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public ru.itis.hrservice.grpc.pb.job.JobResponse.Builder addJobsBuilder(
        int index) {
      return getJobsFieldBuilder().addBuilder(
          index, ru.itis.hrservice.grpc.pb.job.JobResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .JobResponse jobs = 1;</code>
     */
    public java.util.List<ru.itis.hrservice.grpc.pb.job.JobResponse.Builder> 
         getJobsBuilderList() {
      return getJobsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.itis.hrservice.grpc.pb.job.JobResponse, ru.itis.hrservice.grpc.pb.job.JobResponse.Builder, ru.itis.hrservice.grpc.pb.job.JobResponseOrBuilder> 
        getJobsFieldBuilder() {
      if (jobsBuilder_ == null) {
        jobsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ru.itis.hrservice.grpc.pb.job.JobResponse, ru.itis.hrservice.grpc.pb.job.JobResponse.Builder, ru.itis.hrservice.grpc.pb.job.JobResponseOrBuilder>(
                jobs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        jobs_ = null;
      }
      return jobsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetAllJobsResponse)
  }

  // @@protoc_insertion_point(class_scope:GetAllJobsResponse)
  private static final ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse();
  }

  public static ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllJobsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAllJobsResponse>() {
    @java.lang.Override
    public GetAllJobsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAllJobsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAllJobsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itis.hrservice.grpc.pb.job.GetAllJobsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

