// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job.proto

package ru.itis.hrservice.grpc.pb.job;

public final class Job {
  private Job() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JobResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllJobsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllJobsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllJobsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllJobsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tjob.proto\"\030\n\nJobRequest\022\n\n\002id\030\001 \001(\t\".\n" +
      "\013JobResponse\022\n\n\002id\030\001 \001(\t\022\023\n\013requirement\030" +
      "\002 \001(\t\"\023\n\021GetAllJobsRequest\"0\n\022GetAllJobs" +
      "Response\022\032\n\004jobs\030\001 \003(\0132\014.JobResponse2E\n\n" +
      "JobService\0227\n\nGetAllJobs\022\022.GetAllJobsReq" +
      "uest\032\023.GetAllJobsResponse\"\000B!\n\035ru.itis.h" +
      "rservice.grpc.pb.jobP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_JobRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JobRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_JobResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_JobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JobResponse_descriptor,
        new java.lang.String[] { "Id", "Requirement", });
    internal_static_GetAllJobsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetAllJobsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllJobsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllJobsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetAllJobsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllJobsResponse_descriptor,
        new java.lang.String[] { "Jobs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
