// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job.proto

package ru.itis.hrservice.grpc.pb.job;

public interface JobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JobResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string requirement = 2;</code>
   * @return The requirement.
   */
  java.lang.String getRequirement();
  /**
   * <code>string requirement = 2;</code>
   * @return The bytes for requirement.
   */
  com.google.protobuf.ByteString
      getRequirementBytes();
}
